### ISSUE TITLE
[LOST-FEATURE] Using JSONSchema for Tools removes ability to change prompts or fields at query time

### ISSUE THREAD

**Issue by kb-sp** [madebywelch/anthropic-go#34]
**Describe the lost feature**
v3.0.1 switches Properties to InputSchema, which does make sense from a schema/struct perspective.

However, this seems to remove the ability to adjust field descriptions/prompts at query time. For example, one of our field prompts is something like `Return the name of the person mentioned in this text. The answer cannot be %s.`. Because the prompt now lives in the static `jsonschema` tag on a struct, this is no longer possible.

Additionally, while we don't leverage this, pre-v3.0.1 allows a dynamic tool field list (Properties) to be controlled at query time. This could potentially be mitigated with various super-/sub-set schema structs, and is probably slightly antithetical to the concept of a Tool.

I'm being careful not to call this a bug, maybe just a breaking change. And I could be missing an important detail.

But even with a v3 version update where breaking changes from v2 are expected, this may or may not effect other users of this module, and may be worth keeping in mind.

**Comment by madebywelch** [comment]
@ehsanul What are your thoughts on this?

**Comment by madebywelch** [comment]
@kb-sp 

Thank you for bringing this breaking change to my attention. You're correct that the switch from Properties to InputSchema in v3.0.1 has implications for dynamic tool definitions, particularly in two areas:

1. Dynamic field descriptions/prompts at query time
2. Dynamic tool field lists controlled at query time

I apologize for any inconvenience this change has caused. You're right that this is a breaking change rather than a bug.

To address your specific example of dynamic prompts (e.g., "Return the name of the person mentioned in this text. The answer cannot be %s."), I'm considering a few potential solutions:

1. Runtime struct generation: We could provide a helper function to generate structs at runtime, allowing for dynamic field descriptions. For example:

```go
tool := CreateDynamicTool("personInfo", func(excludedName string) *jsonschema.Schema {
    return GenerateInputSchema(struct {
        Name string `json:"name" jsonschema:"description=Return the name of the person mentioned in this text. The answer cannot be ${excludedName}."`
    }{})
})
```

2. Hybrid schema definition: We could introduce a more flexible ToolSchema type that allows for both static and dynamic definitions:

```go
type ToolSchema struct {
    Static  *jsonschema.Schema
    Dynamic func() *jsonschema.Schema
}
```

Regarding the dynamic tool field list, you're right that this is more challenging to replicate with the new structure. Your suggestion of using super-/sub-set schema structs is one potential approach. Another might be to provide a way to merge multiple schemas at runtime.

Questions for you:

1. How frequently do you need to adjust field descriptions/prompts at query time?
2. Can you provide more examples of how you've used dynamic tool field lists in the past?
3. Would either of the proposed solutions (runtime struct generation or hybrid schema definition) meet your needs?
4. Are there other aspects of the dynamic Properties approach that you found particularly useful?

**Comment by kb-sp** [comment]
1. We only have one prompt with the simple use case, but we also have one that uses a (long) dynamic enum list for the LLM to choose from (which I forgot to mention). Even an awkward solution for these cases would be fine. I can also see a slippery slope where trying to fit something like this too deeply into the `jsonschema` concept defeats the purpose of the clean solution.
2. We don't use dynamic tool field lists in the sense of Tool A sometimes has 2 fields and sometimes 3. But we do _generate_ tools, which I go into in 4 below.
3. I'd want the solution to not necessarily over-complicate the clean `jsonschema` concept. Your generator function seems like it would keep the struct definitions cleaner, and the function can be kept "to the side", if that makes sense? Or any similar side-band solution.
4. Not specifically. But one broader concept I've built around is to create vendor-agnostic lower-case "t" tool definitions, which can then be passed down to vendor-specific implementation modules (OpenAI, Cohere, Anthropic, etc). The Property setup allowed this, bnut it's not possible as-is to programmatically convert this agnostic definition into a compile-time `jsonschema` definition.

All that being said, we're actually having better success with more pure prompting/completion options than tool use for extracting schema-ed data. And we don't use tools/function calls right now in their more classic chat-based "get the weather for Cleveland" use case. So in the end, even unsolved this isn't a fatal situation for us.

While I can imagine that there _could_ be use cases that would want dynamic prompts and enums in Tools, I wouldn't advocate for that without having a horse in the race.
